# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weblog',
            name='post_words',
            field=models.TextField(default=''),
        ),
    ]
