# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170722_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weblog',
            name='post_words',
        ),
    ]
