# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_weblog_post_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='weblog',
            name='post_words',
            field=models.TextField(default=''),
        ),
    ]
